apiVersion: v1
kind: Service
metadata:
  name: symbolic-reasoning-service
spec:
  selector:
    app: symbolic-reasoning
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP  # You can change to LoadBalancer or NodePort for external access

---
apiVersion: v1
kind: Service
metadata:
  name: federated-learning-service
spec:
  selector:
    app: federated-learning
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: p2p-network-service
spec:
  selector:
    app: p2p-network
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: db-neo4j-service
spec:
  selector:
    app: db-neo4j
  ports:
    - protocol: TCP
      port: 7474
      targetPort: 7474
    - protocol: TCP
      port: 7687
      targetPort: 7687
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: db-test-service
spec:
  selector:
    app: db-test
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
spec:
  selector:
    app: elasticsearch
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
  type: ClusterIP
