





















































}    }        }            messageTextView.setText(message.getText());        public void bind(MessageItem message) {        }            messageTextView = itemView.findViewById(R.id.message_text);            super(itemView);        public MessageViewHolder(@NonNull View itemView) {        private final TextView messageTextView;    static class MessageViewHolder extends RecyclerView.ViewHolder {    }        return messageList.size();    public int getItemCount() {    @Override    }        holder.bind(message);        MessageItem message = messageList.get(position);    public void onBindViewHolder(@NonNull MessageViewHolder holder, int position) {    @Override    }        return new MessageViewHolder(view);        View view = inflater.inflate(R.layout.item_message, parent, false);    public MessageViewHolder onCreateViewHolder(@NonNull ViewGroup parent, int viewType) {    @Override    @NonNull    }        this.inflater = LayoutInflater.from(context);        this.messageList = messageList;    public ChatAdapter(Context context, List<MessageItem> messageList) {    private final LayoutInflater inflater;    private final List<MessageItem> messageList;public class ChatAdapter extends RecyclerView.Adapter<ChatAdapter.MessageViewHolder> {import java.util.List;import com.mlchatbot.R;import androidx.recyclerview.widget.RecyclerView;import androidx.annotation.NonNull;import android.widget.TextView;import android.view.ViewGroup;import android.view.View;import android.view.LayoutInflater;import android.content.Context;package com.mlchatbot.ui;public class ChatAdapter {
    
}
